# dev
# dev mode run
# Path: Makefile
# Dev start react
dev:
	@echo "Starting dev server"
	@echo "Starting react server"
	@npm start


# install
# install all dependencies using npm
# Path: Makefile
install:
	@echo "Installing dependencies"
	@echo "Installing npm dependencies"
	@npm install

# prod
# start production server
# Path: Makefile
prod:
	@echo "Starting production server"
	@echo "Starting react server"
	@npm run build
	@serve -s build