# fly.toml app configuration file generated for c964-backend-bitter-dew-5048 on 2024-01-20T22:37:44-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "c964-backend-bitter-dew-5048"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
